const initialPhrases = [
  {
    id: 0,
    category: "przysłowia",
    phrase: "Gdzie kucharek sześć tam nie ma co jeść",
  },
  { id: 1, category: "przysłowia", phrase: "Co nagle to po diable" },
  {
    id: 2,
    category: "przysłowia",
    phrase: "Nie chwal dnia przed zachodem słońca",
  },
  { id: 3, category: "przysłowia", phrase: "Kuj żelazo póki gorące" },
  {
    id: 4,
    category: "przysłowia",
    phrase: "Lepszy wróbel w garści niż gołąb na dachu",
  },
  {
    id: 5,
    category: "przysłowia",
    phrase: "Jak sobie pościelisz tak się wyśpisz",
  },
  { id: 6, category: "przysłowia", phrase: "Bez pracy nie ma kołaczy" },
  { id: 7, category: "przysłowia", phrase: "Cicha woda brzegi rwie" },
  { id: 8, category: "przysłowia", phrase: "Zgoda buduje niezgoda rujnuje" },
  {
    id: 9,
    category: "przysłowia",
    phrase: "Nie ma tego złego co by na dobre nie wyszło",
  },
  {
    id: 10,
    category: "przysłowia",
    phrase: "Kto pod kim dołki kopie sam w nie wpada",
  },
  { id: 11, category: "przysłowia", phrase: "Nie szata zdobi człowieka" },
  {
    id: 12,
    category: "przysłowia",
    phrase: "Krowa która dużo ryczy mało mleka daje",
  },
  {
    id: 13,
    category: "przysłowia",
    phrase: "Grosz do grosza a będzie kokosza",
  },
  { id: 14, category: "przysłowia", phrase: "Każdy kij ma dwa końce" },
  { id: 15, category: "przysłowia", phrase: "Czas to pieniądz" },
  {
    id: 16,
    category: "przysłowia",
    phrase: "Kto rano wstaje temu Pan Bóg daje",
  },
  { id: 17, category: "przysłowia", phrase: "Biednemu zawsze wiatr w oczy" },
  { id: 18, category: "przysłowia", phrase: "Jak Kuba Bogu tak Bóg Kubie" },
  {
    id: 19,
    category: "przysłowia",
    phrase: "Darowanemu koniowi w zęby się nie zagląda",
  },
  { id: 20, category: "przysłowia", phrase: "Raz na wozie raz pod wozem" },
  { id: 21, category: "przysłowia", phrase: "Lepiej późno niż wcale" },
  { id: 22, category: "przysłowia", phrase: "Jak cię widzą tak cię piszą" },
  {
    id: 23,
    category: "przysłowia",
    phrase: "Póty dzban wodę nosi póki ucho się nie urwie",
  },
  {
    id: 24,
    category: "przysłowia",
    phrase: "Kto mieczem wojuje od miecza ginie",
  },
  { id: 25, category: "przysłowia", phrase: "Z dużej chmury mały deszcz" },
  { id: 26, category: "przysłowia", phrase: "Lepszy rydz niż nic" },
  {
    id: 27,
    category: "przysłowia",
    phrase: "Nosił wilk razy kilka ponieśli i wilka",
  },
  { id: 28, category: "przysłowia", phrase: "Apetyt rośnie w miarę jedzenia" },
  { id: 29, category: "przysłowia", phrase: "Kto pyta nie błądzi" },
  { id: 30, category: "nazwy dań", phrase: "schabowy z kapustą" },
  { id: 31, category: "nazwy dań", phrase: "pierogi ruskie" },
  { id: 32, category: "nazwy dań", phrase: "barszcz czerwony" },
  { id: 33, category: "nazwy dań", phrase: "żurek z kiełbasą" },
  { id: 34, category: "nazwy dań", phrase: "placki ziemniaczane" },
  { id: 35, category: "nazwy dań", phrase: "kaczka z jabłkami" },
  { id: 36, category: "nazwy dań", phrase: "gołąbki z ryżem" },
  { id: 37, category: "nazwy dań", phrase: "rosół z makaronem" },
  { id: 38, category: "nazwy dań", phrase: "kluski śląskie" },
  { id: 39, category: "nazwy dań", phrase: "gulasz wołowy" },
  { id: 40, category: "nazwy dań", phrase: "karp smażony" },
  { id: 41, category: "nazwy dań", phrase: "sałatka jarzynowa" },
  { id: 42, category: "nazwy dań", phrase: "flaki wołowe" },
  { id: 43, category: "nazwy dań", phrase: "bigos staropolski" },
  { id: 44, category: "nazwy dań", phrase: "kotlet mielony" },
  { id: 45, category: "postacie z bajek", phrase: "Królewna Śnieżka" },
  { id: 46, category: "postacie z bajek", phrase: "Czerwony Kapturek" },
  { id: 47, category: "postacie z bajek", phrase: "Jaś i Małgosia" },
  { id: 48, category: "postacie z bajek", phrase: "Pinokio" },
  { id: 49, category: "postacie z bajek", phrase: "Shrek" },
  { id: 50, category: "postacie z bajek", phrase: "Kot w butach" },
  { id: 51, category: "postacie z bajek", phrase: "Myszka Miki" },
  { id: 52, category: "postacie z bajek", phrase: "Pszczółka Maja" },
  { id: 53, category: "postacie z bajek", phrase: "Kubuś Puchatek" },
  { id: 54, category: "postacie z bajek", phrase: "Kopciuszek" },
  { id: 55, category: "postacie z bajek", phrase: "Herkules" },
  { id: 56, category: "postacie z bajek", phrase: "Arielka" },
  { id: 57, category: "postacie z bajek", phrase: "Elsa" },
  { id: 58, category: "postacie z bajek", phrase: "Piotruś Pan" },
  { id: 59, category: "postacie z bajek", phrase: "Złota Rybka" },
  { id: 60, category: "postacie z bajek", phrase: "Smerfetka" },
  { id: 61, category: "postacie z bajek", phrase: "Aladyn" },
  { id: 62, category: "postacie z bajek", phrase: "Tom i Jerry" },
  { id: 63, category: "postacie z bajek", phrase: "Pocahontas" },
  { id: 64, category: "postacie z bajek", phrase: "Bolek i Lolek" },
  { id: 65, category: "tytuły filmów", phrase: "Gwiezdne Wojny" },
  { id: 66, category: "tytuły filmów", phrase: "Ojciec Chrzestny" },
  { id: 67, category: "tytuły filmów", phrase: "Titanic" },
  { id: 68, category: "tytuły filmów", phrase: "Forrest Gump" },
  { id: 69, category: "tytuły filmów", phrase: "Władca Pierścieni" },
  { id: 70, category: "tytuły filmów", phrase: "Matrix" },
  { id: 71, category: "tytuły filmów", phrase: "Incepcja" },
  { id: 72, category: "tytuły filmów", phrase: "Avatar" },
  { id: 73, category: "tytuły filmów", phrase: "Gladiator" },
  { id: 74, category: "tytuły filmów", phrase: "Jumanji" },
  { id: 75, category: "tytuły filmów", phrase: "Pulp Fiction" },
  { id: 76, category: "tytuły filmów", phrase: "Interstellar" },
  { id: 77, category: "tytuły filmów", phrase: "Terminator" },
  { id: 78, category: "tytuły filmów", phrase: "Siedem" },
  { id: 79, category: "tytuły filmów", phrase: "Człowiek z blizną" },
  { id: 80, category: "tytuły filmów", phrase: "Jurassic Park" },
  { id: 81, category: "tytuły filmów", phrase: "Piękny umysł" },
  { id: 82, category: "tytuły filmów", phrase: "Braveheart" },
  { id: 83, category: "tytuły filmów", phrase: "Shrek" },
  { id: 84, category: "tytuły filmów", phrase: "Wielki Gatsby" },
  {
    id: 85,
    category: "związki frazeologiczne",
    phrase: "Siedzieć jak na szpilkach",
  },
  { id: 86, category: "związki frazeologiczne", phrase: "Mieć muchy w nosie" },
  {
    id: 87,
    category: "związki frazeologiczne",
    phrase: "Spalić za sobą mosty",
  },
  {
    id: 88,
    category: "związki frazeologiczne",
    phrase: "Łapać dwie sroki za ogon",
  },
  {
    id: 89,
    category: "związki frazeologiczne",
    phrase: "Wpaść jak śliwka w kompot",
  },
  {
    id: 90,
    category: "związki frazeologiczne",
    phrase: "Rzucać grochem o ścianę",
  },
  { id: 91, category: "związki frazeologiczne", phrase: "Wyjść na prostą" },
  {
    id: 92,
    category: "związki frazeologiczne",
    phrase: "Siedzieć z założonymi rękami",
  },
  { id: 93, category: "związki frazeologiczne", phrase: "Podkulić ogon" },
  {
    id: 94,
    category: "związki frazeologiczne",
    phrase: "Pójść po rozum do głowy",
  },
  {
    id: 95,
    category: "związki frazeologiczne",
    phrase: "Wbić komuś nóż w plecy",
  },
  {
    id: 96,
    category: "związki frazeologiczne",
    phrase: "Drapać się po głowie",
  },
  {
    id: 97,
    category: "związki frazeologiczne",
    phrase: "Rzucać słowa na wiatr",
  },
  { id: 98, category: "związki frazeologiczne", phrase: "Niebo w gębie" },
  {
    id: 99,
    category: "związki frazeologiczne",
    phrase: "Zawrócić komuś w głowie",
  },
  {
    id: 100,
    category: "związki frazeologiczne",
    phrase: "Robić dobrą minę do złej gry",
  },
  { id: 101, category: "związki frazeologiczne", phrase: "Dzień jak co dzień" },
  { id: 102, category: "związki frazeologiczne", phrase: "Jak pies z kotem" },
  {
    id: 103,
    category: "związki frazeologiczne",
    phrase: "Grać pierwsze skrzypce",
  },
  {
    id: 104,
    category: "związki frazeologiczne",
    phrase: "Mieć serce na dłoni",
  },
  {
    id: 105,
    category: "związki frazeologiczne",
    phrase: "Czuć się jak ryba w wodzie",
  },
  { id: 106, category: "związki frazeologiczne", phrase: "Być na wagę złota" },
  {
    id: 107,
    category: "związki frazeologiczne",
    phrase: "Mieć motyle w brzuchu",
  },
  { id: 108, category: "związki frazeologiczne", phrase: "Pięta Achillesa" },
  {
    id: 109,
    category: "związki frazeologiczne",
    phrase: "Przegapić swoją szansę",
  },
  {
    id: 110,
    category: "związki frazeologiczne",
    phrase: "Chować głowę w piasek",
  },
  {
    id: 111,
    category: "związki frazeologiczne",
    phrase: "Być w siódmym niebie",
  },
  {
    id: 112,
    category: "związki frazeologiczne",
    phrase: "Trzymać język za zębami",
  },
  { id: 113, category: "związki frazeologiczne", phrase: "Pójść na całość" },
  {
    id: 114,
    category: "związki frazeologiczne",
    phrase: "Iść po nitce do kłębka",
  },
  {
    id: 115,
    category: "związki frazeologiczne",
    phrase: "Kopać pod kimś dołki",
  },
  { id: 116, category: "znane postacie", phrase: "Albert Einstein" },
  { id: 117, category: "znane postacie", phrase: "Mikołaj Kopernik" },
  { id: 118, category: "znane postacie", phrase: "Maria Skłodowska Curie" },
  { id: 119, category: "znane postacie", phrase: "Napoleon Bonaparte" },
  { id: 120, category: "znane postacie", phrase: "William Shakespeare" },
  { id: 121, category: "znane postacie", phrase: "Juliusz Cezar" },
  { id: 122, category: "znane postacie", phrase: "Leonardo da Vinci" },
  { id: 123, category: "znane postacie", phrase: "Mahatma Gandhi" },
  { id: 124, category: "znane postacie", phrase: "Ludwig van Beethoven" },
  { id: 125, category: "znane postacie", phrase: "Abraham Lincoln" },
  { id: 126, category: "znane postacie", phrase: "Elvis Presley" },
  { id: 127, category: "znane postacie", phrase: "Fryderyk Chopin" },
  { id: 128, category: "znane postacie", phrase: "Isaac Newton" },
  { id: 129, category: "znane postacie", phrase: "Winston Churchill" },
  { id: 130, category: "znane postacie", phrase: "Nelson Mandela" },
  { id: 131, category: "znane postacie", phrase: "Walt Disney" },
  { id: 132, category: "znane postacie", phrase: "Pablo Picasso" },
  { id: 133, category: "znane postacie", phrase: "Krzysztof Ibisz" },
  { id: 134, category: "znane postacie", phrase: "Charlie Chaplin" },
  { id: 135, category: "znane postacie", phrase: "Barack Obama" },

  { id: 136, category: "tytuły książek", phrase: "Pan Tadeusz" },
  { id: 137, category: "tytuły książek", phrase: "Zbrodnia i kara" },
  {
    id: 138,
    category: "tytuły książek",
    phrase: "Harry Potter i Kamień Filozoficzny",
  },
  {
    id: 139,
    category: "tytuły książek",
    phrase: "Hobbit czyli tam i z powrotem",
  },
  { id: 140, category: "tytuły książek", phrase: "Mały Książę" },
  { id: 141, category: "tytuły książek", phrase: "W pustyni i w puszczy" },
  { id: 142, category: "tytuły książek", phrase: "Opowieść wigilijna" },
  { id: 143, category: "tytuły książek", phrase: "Mistrz i Małgorzata" },
  { id: 144, category: "tytuły książek", phrase: "Ania z Zielonego Wzgórza" },
  { id: 145, category: "tytuły książek", phrase: "Władca Pierścieni" },
  { id: 146, category: "tytuły książek", phrase: "Przeminęło z wiatrem" },

  {
    id: 148,
    category: "łamańce językowe",
    phrase: "Król Karol kupił królowej Karolinie korale koloru koralowego",
  },
  {
    id: 149,
    category: "łamańce językowe",
    phrase: "Stół z powyłamywanymi nogami",
  },
  {
    id: 150,
    category: "łamańce językowe",
    phrase: "Czarna krowa w kropki bordo gryzła trawę kręcąc mordą",
  },

  { id: 151, category: "łamańce językowe", phrase: "Szedł Sasza suchą szosą" },
  {
    id: 152,
    category: "łamańce językowe",
    phrase: "Czy tata czyta cytaty Tacyta",
  },
  { id: 153, category: "łamańce językowe", phrase: "I cóż że ze Szwecji" },

  { id: 154, category: "nazwy geograficzne", phrase: "Góry Świętokrzyskie" },
  { id: 155, category: "nazwy geograficzne", phrase: "Wielki Kanion Kolorado" },
  {
    id: 156,
    category: "nazwy geograficzne",
    phrase: "Przylądek Dobrej Nadziei",
  },
  { id: 157, category: "nazwy geograficzne", phrase: "Zatoka Meksykańska" },
  { id: 158, category: "nazwy geograficzne", phrase: "Morze Północne" },
  { id: 159, category: "nazwy geograficzne", phrase: "Morze Martwe" },
  {
    id: 160,
    category: "nazwy geograficzne",
    phrase: "Jezioro Białe Augustowskie",
  },
  {
    id: 161,
    category: "nazwy geograficzne",
    phrase: "Wyspy Zielonego Przylądka",
  },
  { id: 162, category: "nazwy geograficzne", phrase: "Półwysep Iberyjski" },
  { id: 163, category: "nazwy geograficzne", phrase: "Morze Czerwone" },
  { id: 164, category: "nazwy geograficzne", phrase: "Góry Skaliste" },
  { id: 166, category: "nazwy geograficzne", phrase: "Pustynia Atakama" },
  { id: 167, category: "nazwy geograficzne", phrase: "Wyżyna Tybetańska" },
  { id: 168, category: "nazwy geograficzne", phrase: "Dolina Krzemowa" },
  { id: 169, category: "nazwy geograficzne", phrase: "Wielka Rafa Koralowa" },
  { id: 170, category: "nazwy geograficzne", phrase: "Zatoka Biskajska" },
  { id: 171, category: "nazwy geograficzne", phrase: "Wyspy Kanaryjskie" },
  { id: 172, category: "nazwy geograficzne", phrase: "Pustynia Gobi" },
  { id: 173, category: "nazwy geograficzne", phrase: "Równina Amazonki" },

  { id: 174, category: "polskie województwa", phrase: "Dolnośląskie" },
  { id: 175, category: "polskie województwa", phrase: "Kujawsko Pomorskie" },
  { id: 176, category: "polskie województwa", phrase: "Lubelskie" },
  { id: 177, category: "polskie województwa", phrase: "Lubuskie" },
  { id: 178, category: "polskie województwa", phrase: "Łódzkie" },
  { id: 179, category: "polskie województwa", phrase: "Małopolskie" },
  { id: 180, category: "polskie województwa", phrase: "Mazowieckie" },
  { id: 181, category: "polskie województwa", phrase: "Opolskie" },
  { id: 182, category: "polskie województwa", phrase: "Podkarpackie" },
  { id: 183, category: "polskie województwa", phrase: "Podlaskie" },
  { id: 184, category: "polskie województwa", phrase: "Pomorskie" },
  { id: 185, category: "polskie województwa", phrase: "Śląskie" },
  { id: 186, category: "polskie województwa", phrase: "Świętokrzyskie" },
  { id: 187, category: "polskie województwa", phrase: "Warmińsko Mazurskie" },
  { id: 188, category: "polskie województwa", phrase: "Wielkopolskie" },
  { id: 189, category: "polskie województwa", phrase: "Zachodniopomorskie" },

  { id: 209, category: "nazwy dań", phrase: "krem z pomidorów" },
  { id: 210, category: "nazwy dań", phrase: "placek po węgiersku" },
  { id: 211, category: "nazwy dań", phrase: "łazanki z kapustą" },
  { id: 212, category: "nazwy dań", phrase: "gofry z bitą śmietaną" },

  { id: 205, category: "związki frazeologiczne", phrase: "Wylać dziecko z kąpielą" },
  { id: 206, category: "związki frazeologiczne", phrase: "Chcieć gwiazdkę z nieba" },
  { id: 207, category: "związki frazeologiczne", phrase: "Grać va banque" },
  { id: 208, category: "związki frazeologiczne", phrase: "Mieć z kimś kosę" },

  { id: 190, category: "przysłowia", phrase: "Nadzieja matką głupich" },
  { id: 191, category: "przysłowia", phrase: "Jak się nie ma co się lubi to się lubi co się ma" },
  { id: 192, category: "przysłowia", phrase: "Kto się boi, ten dwa razy traci" },
  { id: 193, category: "przysłowia", phrase: "Gdzie drwa rąbią tam wióry lecą" },

  { id: 231, category: "znane postacie", phrase: "Józef Piłsudski" },
  { id: 232, category: "znane postacie", phrase: "Kazimierz Wielki" },
  { id: 233, category: "znane postacie", phrase: "Tadeusz Kościuszko" },
  { id: 235, category: "znane postacie", phrase: "Władysław Jagiełło" },
  { id: 236, category: "znane postacie", phrase: "Adam Mickiewicz" },
  { id: 237, category: "znane postacie", phrase: "Stanisław August Poniatowski" },
  { id: 238, category: "znane postacie", phrase: "Henryk Sienkiewicz" },
  { id: 239, category: "znane postacie", phrase: "Fryderyk Chopin" },
  { id: 240, category: "znane postacie", phrase: "Józef Bem" },

  { id: 261, category: "polskie seriale", phrase: "Czterej pancerni i pies" },
  { id: 262, category: "polskie seriale", phrase: "Stawka większa niż życie" },
  { id: 264, category: "polskie seriale", phrase: "Zmiennicy" },
  { id: 265, category: "polskie seriale", phrase: "Ranczo" },
  { id: 266, category: "polskie seriale", phrase: "Rodzinka pl" },
  { id: 267, category: "polskie seriale", phrase: "Świat według Kiepskich" },
  { id: 268, category: "polskie seriale", phrase: "Ojciec Mateusz" },
  { id: 269, category: "polskie seriale", phrase: "Klan" },
  { id: 270, category: "polskie seriale", phrase: "Na dobre i na złe" },

  { id: 271, category: "polskie teleturnieje", phrase: "Milionerzy" },
  { id: 272, category: "polskie teleturnieje", phrase: "Familiada" },
  { id: 273, category: "polskie teleturnieje", phrase: "Koło Fortuny" },
  { id: 274, category: "polskie teleturnieje", phrase: "Jaka to melodia?" },
  { id: 275, category: "polskie teleturnieje", phrase: "Jeden z dziesięciu" },
  { id: 276, category: "polskie teleturnieje", phrase: "Postaw na milion" },
  { id: 277, category: "polskie teleturnieje", phrase: "Va banque" },
  { id: 278, category: "polskie teleturnieje", phrase: "Twoja twarz brzmi znajomo" },
  { id: 279, category: "polskie teleturnieje", phrase: "The Voice of Poland" },
  { id: 280, category: "polskie teleturnieje", phrase: "Mam talent" },
];
const vowels = ["A", "E", "I", "O", "U", "Y", "Ą", "Ę", "Ó"];

const values = [
  "-100%",
  250,
  400,
  300,
  1500,
  600,
  700,
  800,
  "STOP",
  600,
  200,
  100,
  1000,
  500,
  800,
  150,
];

module.exports = { initialPhrases, vowels, values };
