const initialPhrases = [
  'Z małej chmury duży deszcz',
  'Co nagle to po diable',
  'Lepszy wróbel w garści',
  'Kto pyta nie błądzi',
  'Czas leczy rany',
  'Bez pracy nie ma kołaczy',
  'Prawda w oczy kole',
  'Kto pod kim dołki kopie',
  'Gdzie kucharek sześć tam nie ma co jeść',
  'Nie ma tego złego co by na dobre nie wyszło',
  'Jak sobie pościelesz tak się wyśpisz',
  'Nie wszystko złoto co się świeci',
  'Każdy kij ma dwa końce',
  'Darowanemu koniowi nie zagląda się w zęby',
  'Co za dużo to niezdrowo',
  'Biednemu zawsze wiatr w oczy',
  'Co kraj to obyczaj',
  'Gdzie drwa rąbią tam wióry lecą',
  'Lepszy późno niż wcale',
  'Nie chwal dnia przed zachodem słońca',
  'Nie ma róży bez kolców',
  'Jak cię widzą tak cię piszą',
  'Co dwie głowy to nie jedna',
  'Mowa jest srebrem a milczenie złotem',
  'Gdzie diabeł nie może tam babę pośle',
  'Z próżnego i Salomon nie naleje',
  'Pieniądze szczęścia nie dają',
  'Kiedy wejdziesz między wrony musisz krakać jak i one',
  'Nie taki diabeł straszny jak go malują',
  'Ręka rękę myje',
  'Lepiej późno niż wcale',
  'Kto sieje wiatr ten zbiera burzę',
  'Cicha woda brzegi rwie',
  'Głodnemu chleb na myśli',
  'Na bezrybiu i rak ryba',
  'Nie ma dymu bez ognia',
  'Póty dzban wodę nosi aż się rozleje',
  'Strach ma wielkie oczy',
  'Wilk syty i owca cała',
  'Gdzie serce nie sięga tam ucho nie dochodzi',
  'Kto nie ryzykuje ten nie pije szampana',
  'Kto szuka znajdzie',
  'Na marnym garnku nauczka',
  'Nie święci garnki lepią',
  'Jaka praca to tańsza suknia',
  'Lepszy wróbel w garści niż gołąb na dachu',
  'Kto pod kim dołki kopie sam w nie wpada',
  'Pies, który dużo szczeka nie gryzie',
  'Gdy kota nie ma myszy harcują',
  'Lepszy jeden wróbel w garści niż dziesięć na dachu',
  'Kto rano wstaje temu Pan Bóg daje'
];


const vowels = ['A', 'E', 'I', 'O', 'U', 'Y', 'Ą', 'Ę', 'Ó'];

const values = [
  '-100%',
  1000,
  400,
  300,
  150,
  600,
  700,
  800,
  'STOP',
  600,
  200,
  100,
  250,
  500,
  800,
  1500,
];

module.exports = { initialPhrases, vowels, values };
