const initialPhrases = [
  // Łamańce językowe
  {
    id: 0,
    category: "łamańce językowe",
    phrase: "Chrząszcz brzmi w trzcinie w Szczebrzeszynie",
  },
  {
    id: 1,
    category: "łamańce językowe",
    phrase: "Czy tata czyta cytaty Tacyta",
  },
  {
    id: 2,
    category: "łamańce językowe",
    phrase: "Czarna krowa w kropki bordo gryzła trawę kręcąc mordą",
  },
  { id: 3, category: "łamańce językowe", phrase: "I cóż że ze Szwecji" },
  { id: 4, category: "łamańce językowe", phrase: "Koszt poczt w Tczewie" },
  {
    id: 5,
    category: "łamańce językowe",
    phrase: "Król Karol kupił królowej Karolinie korale koloru koralowego",
  },
  {
    id: 6,
    category: "łamańce językowe",
    phrase: "Stół z powyłamywanymi nogami",
  },
  { id: 7, category: "łamańce językowe", phrase: "Szedł Sasza suchą szosą" },
  // {
  //   id: 8,
  //   category: "łamańce językowe",
  //   phrase: "W Szczebrzeszynie chrząszcz brzmi w trzcinie",
  // },
  // {
  //   id: 9,
  //   category: "łamańce językowe",
  //   phrase: "Wyindywidualizowaliśmy się z rozentuzjazmowanego tłumu",
  // },
  { id: 10, category: "łamańce językowe", phrase: "Pocztmistrz z Tczewa" },
  {
    id: 11,
    category: "łamańce językowe",
    phrase: "Sześć szóstek ssało szare szmatki",
  },

  // Nazwy dań
  { id: 12, category: "nazwy dań", phrase: "Barszcz czerwony" },
  { id: 13, category: "nazwy dań", phrase: "Bigos staropolski" },
  { id: 14, category: "nazwy dań", phrase: "Flaki wołowe" },
  { id: 15, category: "nazwy dań", phrase: "Gofry z bitą śmietaną" },
  { id: 16, category: "nazwy dań", phrase: "Gołąbki z ryżem" },
  { id: 17, category: "nazwy dań", phrase: "Gulasz wołowy" },
  { id: 18, category: "nazwy dań", phrase: "Kaczka z jabłkami" },
  { id: 19, category: "nazwy dań", phrase: "Karp smażony" },
  { id: 20, category: "nazwy dań", phrase: "Kebab na frytkach" },
  { id: 21, category: "nazwy dań", phrase: "Klopsiki w sosie pomidorowym" },
  { id: 22, category: "nazwy dań", phrase: "Kluski śląskie" },
  { id: 23, category: "nazwy dań", phrase: "Kotlet mielony" },
  { id: 24, category: "nazwy dań", phrase: "Krem z pomidorów" },
  { id: 25, category: "nazwy dań", phrase: "Krokiety z mięsem" },
  { id: 26, category: "nazwy dań", phrase: "Kurczak pieczony" },
  { id: 27, category: "nazwy dań", phrase: "Łazanki z kapustą" },
  { id: 28, category: "nazwy dań", phrase: "Naleśniki z serem" },
  { id: 29, category: "nazwy dań", phrase: "Pierogi ruskie" },
  { id: 30, category: "nazwy dań", phrase: "Placki ziemniaczane" },
  { id: 31, category: "nazwy dań", phrase: "Placek po węgiersku" },
  { id: 32, category: "nazwy dań", phrase: "Rosół z makaronem" },
  { id: 33, category: "nazwy dań", phrase: "Sałatka grecka" },
  { id: 34, category: "nazwy dań", phrase: "Sałatka jarzynowa" },
  { id: 35, category: "nazwy dań", phrase: "Schabowy z kapustą" },
  { id: 36, category: "nazwy dań", phrase: "Sernik krakowski" },
  { id: 37, category: "nazwy dań", phrase: "Żurek z kiełbasą" },
  { id: 38, category: "nazwy dań", phrase: "Zrazy wołowe" },
  { id: 39, category: "nazwy dań", phrase: "Zupa ogórkowa" },
  { id: 40, category: "nazwy dań", phrase: "Kopytka z sosem grzybowym" },
  { id: 41, category: "nazwy dań", phrase: "Ryba po grecku" },
  { id: 42, category: "nazwy dań", phrase: "Kapuśniak" },
  { id: 43, category: "nazwy dań", phrase: "Kompot z suszu" },

  // Nazwy geograficzne
  { id: 44, category: "nazwy geograficzne", phrase: "Dolina Krzemowa" },
  { id: 45, category: "nazwy geograficzne", phrase: "Góry Skaliste" },
  { id: 46, category: "nazwy geograficzne", phrase: "Góry Świętokrzyskie" },
  {
    id: 47,
    category: "nazwy geograficzne",
    phrase: "Ocean indyjski",
  },
  { id: 48, category: "nazwy geograficzne", phrase: "Morze Bałtyckie" },
  { id: 49, category: "nazwy geograficzne", phrase: "Morze Czerwone" },
  { id: 50, category: "nazwy geograficzne", phrase: "Morze Martwe" },
  { id: 51, category: "nazwy geograficzne", phrase: "Morze Północne" },
  { id: 52, category: "nazwy geograficzne", phrase: "Półwysep Iberyjski" },
  {
    id: 53,
    category: "nazwy geograficzne",
    phrase: "Przylądek Dobrej Nadziei",
  },
  { id: 54, category: "nazwy geograficzne", phrase: "Pustynia Atakama" },
  { id: 55, category: "nazwy geograficzne", phrase: "Pustynia Gobi" },
  { id: 56, category: "nazwy geograficzne", phrase: "Równina Amazonki" },
  { id: 57, category: "nazwy geograficzne", phrase: "Tatry Wysokie" },
  { id: 58, category: "nazwy geograficzne", phrase: "Wielka Rafa Koralowa" },
  { id: 59, category: "nazwy geograficzne", phrase: "Wielki Kanion Kolorado" },
  { id: 60, category: "nazwy geograficzne", phrase: "Wyspa Wielkanocna" },
  { id: 61, category: "nazwy geograficzne", phrase: "Wyspy Kanaryjskie" },
  {
    id: 62,
    category: "nazwy geograficzne",
    phrase: "Wyspy Zielonego Przylądka",
  },
  { id: 63, category: "nazwy geograficzne", phrase: "Półwysep helski" },
  { id: 64, category: "nazwy geograficzne", phrase: "Zatoka Meksykańska" },
  { id: 65, category: "nazwy geograficzne", phrase: "Delta Nilu" },
  { id: 66, category: "nazwy geograficzne", phrase: "Rów Mariański" },
  { id: 67, category: "nazwy geograficzne", phrase: "Pustynia Sahara" },

  // Polskie seriale
  { id: 68, category: "polskie seriale", phrase: "Czterej pancerni i pies" },
  { id: 69, category: "polskie seriale", phrase: "Klan" },
  { id: 70, category: "polskie seriale", phrase: "M jak miłość" },
  { id: 71, category: "polskie seriale", phrase: "Na dobre i na złe" },
  { id: 72, category: "polskie seriale", phrase: "Ojciec Mateusz" },
  { id: 73, category: "polskie seriale", phrase: "Ranczo" },
  { id: 74, category: "polskie seriale", phrase: "Rodzinka pl" },
  { id: 75, category: "polskie seriale", phrase: "Stawka większa niż życie" },
  { id: 76, category: "polskie seriale", phrase: "Świat według Kiepskich" },
  { id: 77, category: "polskie seriale", phrase: "Zmiennicy" },
  { id: 79, category: "polskie seriale", phrase: "Barwy szczęścia" },
  { id: 80, category: "polskie seriale", phrase: "Pierwsza miłość" },

  // Polskie teleturnieje
  { id: 81, category: "polskie teleturnieje", phrase: "Familiada" },
  { id: 82, category: "polskie teleturnieje", phrase: "Jaka to melodia" },
  { id: 83, category: "polskie teleturnieje", phrase: "Jeden z dziesięciu" },
  { id: 84, category: "polskie teleturnieje", phrase: "Koło Fortuny" },
  { id: 85, category: "polskie teleturnieje", phrase: "Mam talent" },
  { id: 86, category: "polskie teleturnieje", phrase: "Milionerzy" },
  { id: 87, category: "polskie teleturnieje", phrase: "Postaw na milion" },
  { id: 88, category: "polskie teleturnieje", phrase: "The Voice of Poland" },
  {
    id: 89,
    category: "polskie teleturnieje",
    phrase: "Twoja twarz brzmi znajomo",
  },
  { id: 90, category: "polskie teleturnieje", phrase: "Va banque" },
  { id: 91, category: "polskie teleturnieje", phrase: "Taniec z gwiazdami" },
  { id: 92, category: "polskie teleturnieje", phrase: "Big Brother" },

  // Polskie województwa
  { id: 93, category: "polskie województwa", phrase: "Dolnośląskie" },
  { id: 94, category: "polskie województwa", phrase: "Kujawsko Pomorskie" },
  { id: 95, category: "polskie województwa", phrase: "Lubelskie" },
  { id: 96, category: "polskie województwa", phrase: "Lubuskie" },
  { id: 97, category: "polskie województwa", phrase: "Łódzkie" },
  { id: 98, category: "polskie województwa", phrase: "Małopolskie" },
  { id: 99, category: "polskie województwa", phrase: "Mazowieckie" },
  { id: 100, category: "polskie województwa", phrase: "Opolskie" },
  { id: 101, category: "polskie województwa", phrase: "Podkarpackie" },
  { id: 102, category: "polskie województwa", phrase: "Podlaskie" },
  { id: 103, category: "polskie województwa", phrase: "Pomorskie" },
  { id: 104, category: "polskie województwa", phrase: "Śląskie" },
  { id: 105, category: "polskie województwa", phrase: "Świętokrzyskie" },
  { id: 106, category: "polskie województwa", phrase: "Warmińsko Mazurskie" },
  { id: 107, category: "polskie województwa", phrase: "Wielkopolskie" },
  // { id: 108, category: "polskie województwa", phrase: "Zachodniopomorskie" },

  // Postacie z bajek
  { id: 109, category: "postacie z bajek", phrase: "Aladyn" },
  { id: 110, category: "postacie z bajek", phrase: "Arielka" },
  { id: 111, category: "postacie z bajek", phrase: "Bolek i Lolek" },
  { id: 112, category: "postacie z bajek", phrase: "Czerwony Kapturek" },
  { id: 113, category: "postacie z bajek", phrase: "Elsa" },
  { id: 114, category: "postacie z bajek", phrase: "Gumisie" },
  { id: 115, category: "postacie z bajek", phrase: "Herkules" },
  { id: 116, category: "postacie z bajek", phrase: "Jaś i Małgosia" },
  { id: 117, category: "postacie z bajek", phrase: "Kopciuszek" },
  { id: 118, category: "postacie z bajek", phrase: "Kot w butach" },
  { id: 119, category: "postacie z bajek", phrase: "Krecik" },
  { id: 120, category: "postacie z bajek", phrase: "Król Lew" },
  { id: 121, category: "postacie z bajek", phrase: "Królewna Śnieżka" },
  { id: 122, category: "postacie z bajek", phrase: "Królik Bugs" },
  { id: 123, category: "postacie z bajek", phrase: "Kubuś Puchatek" },
  { id: 124, category: "postacie z bajek", phrase: "Myszka Miki" },
  { id: 125, category: "postacie z bajek", phrase: "Piotruś Pan" },
  { id: 126, category: "postacie z bajek", phrase: "Pocahontas" },
  { id: 127, category: "postacie z bajek", phrase: "Pinokio" },
  { id: 128, category: "postacie z bajek", phrase: "Pszczółka Maja" },
  { id: 129, category: "postacie z bajek", phrase: "Scooby Doo" },
  { id: 130, category: "postacie z bajek", phrase: "Shrek" },
  { id: 131, category: "postacie z bajek", phrase: "Smerfetka" },
  { id: 132, category: "postacie z bajek", phrase: "SpongeBob Kanciastoporty" },
  { id: 133, category: "postacie z bajek", phrase: "Tom i Jerry" },
  { id: 134, category: "postacie z bajek", phrase: "Wilk i Zając" },
  { id: 135, category: "postacie z bajek", phrase: "Złota Rybka" },

  // Przysłowia
  { id: 136, category: "przysłowia", phrase: "Apetyt rośnie w miarę jedzenia" },
  { id: 137, category: "przysłowia", phrase: "Bez pracy nie ma kołaczy" },
  { id: 138, category: "przysłowia", phrase: "Biednemu zawsze wiatr w oczy" },
  { id: 139, category: "przysłowia", phrase: "Co nagle to po diable" },
  { id: 140, category: "przysłowia", phrase: "Cicha woda brzegi rwie" },
  { id: 141, category: "przysłowia", phrase: "Czas to pieniądz" },
  {
    id: 142,
    category: "przysłowia",
    phrase: "Darowanemu koniowi w zęby się nie zagląda",
  },
  {
    id: 143,
    category: "przysłowia",
    phrase: "Gdyby kózka nie skakała to by nóżki nie złamała",
  },
  {
    id: 144,
    category: "przysłowia",
    phrase: "Gdzie drwa rąbią tam wióry lecą",
  },
  {
    id: 145,
    category: "przysłowia",
    phrase: "Gdzie kucharek sześć tam nie ma co jeść",
  },
  {
    id: 146,
    category: "przysłowia",
    phrase: "Grosz do grosza a będzie kokosza",
  },
  { id: 147, category: "przysłowia", phrase: "Jak cię widzą tak cię piszą" },
  { id: 148, category: "przysłowia", phrase: "Jak Kuba Bogu tak Bóg Kubie" },
  {
    id: 149,
    category: "przysłowia",
    phrase: "Jak sobie pościelisz tak się wyśpisz",
  },
  {
    id: 150,
    category: "przysłowia",
    phrase: "Jak się nie ma co się lubi to się lubi co się ma",
  },
  { id: 151, category: "przysłowia", phrase: "Każdy kij ma dwa końce" },
  {
    id: 152,
    category: "przysłowia",
    phrase: "Kiedy wejdziesz między wrony musisz krakać jak i one",
  },
  {
    id: 153,
    category: "przysłowia",
    phrase: "Kto mieczem wojuje od miecza ginie",
  },
  {
    id: 154,
    category: "przysłowia",
    phrase: "Kto pod kim dołki kopie sam w nie wpada",
  },
  {
    id: 155,
    category: "przysłowia",
    phrase: "Kto rano wstaje temu Pan Bóg daje",
  },
  { id: 156, category: "przysłowia", phrase: "Kuj żelazo póki gorące" },
  {
    id: 157,
    category: "przysłowia",
    phrase: "Lepszy wróbel w garści niż gołąb na dachu",
  },
  { id: 158, category: "przysłowia", phrase: "Lepszy rydz niż nic" },
  { id: 159, category: "przysłowia", phrase: "Lepiej późno niż wcale" },
  { id: 160, category: "przysłowia", phrase: "Mądry Polak po szkodzie" },
  { id: 161, category: "przysłowia", phrase: "Nadzieja matką głupich" },
  {
    id: 162,
    category: "przysłowia",
    phrase: "Nie chwal dnia przed zachodem słońca",
  },
  {
    id: 163,
    category: "przysłowia",
    phrase: "Nie ma tego złego co by na dobre nie wyszło",
  },
  { id: 164, category: "przysłowia", phrase: "Nie szata zdobi człowieka" },
  {
    id: 165,
    category: "przysłowia",
    phrase: "Nosił wilk razy kilka ponieśli i wilka",
  },
  { id: 166, category: "przysłowia", phrase: "Pieniądze szczęścia nie dają" },
  {
    id: 167,
    category: "przysłowia",
    phrase: "Przyjaciół poznaje się w biedzie",
  },
  {
    id: 168,
    category: "przysłowia",
    phrase: "Póty dzban wodę nosi póki ucho się nie urwie",
  },
  { id: 169, category: "przysłowia", phrase: "Raz na wozie raz pod wozem" },
  { id: 170, category: "przysłowia", phrase: "Z dużej chmury mały deszcz" },
  { id: 171, category: "przysłowia", phrase: "Zgoda buduje niezgoda rujnuje" },
  { id: 172, category: "przysłowia", phrase: "Kto się boi ten dwa razy traci" },
  { id: 173, category: "przysłowia", phrase: "Gdy kota nie ma myszy harcują" },
  {
    id: 174,
    category: "przysłowia",
    phrase: "Nie wszystko złoto co się świeci",
  },
  { id: 175, category: "przysłowia", phrase: "Śmiech to zdrowie" },

  // Tytuły filmów
  { id: 176, category: "tytuły filmów", phrase: "Avatar" },
  { id: 177, category: "tytuły filmów", phrase: "Braveheart" },
  { id: 178, category: "tytuły filmów", phrase: "Człowiek z blizną" },
  { id: 179, category: "tytuły filmów", phrase: "Forrest Gump" },
  { id: 180, category: "tytuły filmów", phrase: "Gladiator" },
  { id: 181, category: "tytuły filmów", phrase: "Gwiezdne Wojny" },
  { id: 182, category: "tytuły filmów", phrase: "Incepcja" },
  { id: 183, category: "tytuły filmów", phrase: "Interstellar" },
  { id: 184, category: "tytuły filmów", phrase: "Jumanji" },
  { id: 185, category: "tytuły filmów", phrase: "Jurassic Park" },
  { id: 186, category: "tytuły filmów", phrase: "Matrix" },
  { id: 187, category: "tytuły filmów", phrase: "Ojciec Chrzestny" },
  { id: 188, category: "tytuły filmów", phrase: "Piraci z Karaibów" },
  { id: 189, category: "tytuły filmów", phrase: "Pulp Fiction" },
  { id: 190, category: "tytuły filmów", phrase: "Shrek" },
  { id: 191, category: "tytuły filmów", phrase: "Siedem" },
  { id: 192, category: "tytuły filmów", phrase: "Terminator" },
  { id: 193, category: "tytuły filmów", phrase: "Titanic" },
  { id: 194, category: "tytuły filmów", phrase: "Wielki Gatsby" },
  { id: 195, category: "tytuły filmów", phrase: "Władca Pierścieni" },
  { id: 196, category: "tytuły filmów", phrase: "Piękny umysł" },
  { id: 197, category: "tytuły filmów", phrase: "Matrix Reaktywacja" },
  { id: 198, category: "tytuły filmów", phrase: "Iron Man" },
  { id: 199, category: "tytuły filmów", phrase: "Sherlock Holmes" },
  { id: 200, category: "tytuły filmów", phrase: "Skazani na Shawshank" },

  // Tytuły książek
  { id: 201, category: "tytuły książek", phrase: "Ania z Zielonego Wzgórza" },
  { id: 202, category: "tytuły książek", phrase: "Chłopi" },
  { id: 203, category: "tytuły książek", phrase: "Dziady" },
  {
    id: 204,
    category: "tytuły książek",
    phrase: "Harry Potter i Kamień Filozoficzny",
  },
  {
    id: 205,
    category: "tytuły książek",
    phrase: "Hobbit czyli tam i z powrotem",
  },
  { id: 206, category: "tytuły książek", phrase: "Krzyżacy" },
  { id: 207, category: "tytuły książek", phrase: "Lalka" },
  { id: 208, category: "tytuły książek", phrase: "Mały Książę" },
  { id: 209, category: "tytuły książek", phrase: "Mistrz i Małgorzata" },
  { id: 210, category: "tytuły książek", phrase: "Opowieść wigilijna" },
  { id: 211, category: "tytuły książek", phrase: "Pan Tadeusz" },
  { id: 212, category: "tytuły książek", phrase: "Potop" },
  { id: 213, category: "tytuły książek", phrase: "Przeminęło z wiatrem" },
  { id: 214, category: "tytuły książek", phrase: "Quo Vadis" },
  { id: 215, category: "tytuły książek", phrase: "W pustyni i w puszczy" },
  { id: 216, category: "tytuły książek", phrase: "Władca Pierścieni" },
  { id: 217, category: "tytuły książek", phrase: "Zbrodnia i kara" },
  { id: 218, category: "tytuły książek", phrase: "Przygody Sherlocka Holmesa" },
  { id: 219, category: "tytuły książek", phrase: "Janko muzykant" },
  { id: 220, category: "tytuły książek", phrase: "Chłopcy z placu broni" },

  // Związki frazeologiczne
  { id: 221, category: "związki frazeologiczne", phrase: "Być na wagę złota" },
  {
    id: 222,
    category: "związki frazeologiczne",
    phrase: "Być w siódmym niebie",
  },
  {
    id: 223,
    category: "związki frazeologiczne",
    phrase: "Chować głowę w piasek",
  },
  {
    id: 224,
    category: "związki frazeologiczne",
    phrase: "Czuć się jak ryba w wodzie",
  },
  {
    id: 225,
    category: "związki frazeologiczne",
    phrase: "Drapać się po głowie",
  },
  {
    id: 226,
    category: "związki frazeologiczne",
    phrase: "Grać pierwsze skrzypce",
  },
  { id: 227, category: "związki frazeologiczne", phrase: "Grać va banque" },
  {
    id: 228,
    category: "związki frazeologiczne",
    phrase: "Iść po nitce do kłębka",
  },
  { id: 229, category: "związki frazeologiczne", phrase: "Jak pies z kotem" },
  {
    id: 230,
    category: "związki frazeologiczne",
    phrase: "Kopać pod kimś dołki",
  },
  {
    id: 231,
    category: "związki frazeologiczne",
    phrase: "Łapać dwie sroki za ogon",
  },
  {
    id: 232,
    category: "związki frazeologiczne",
    phrase: "Mieć głowę na karku",
  },
  {
    id: 233,
    category: "związki frazeologiczne",
    phrase: "Mieć motyle w brzuchu",
  },
  { id: 234, category: "związki frazeologiczne", phrase: "Mieć muchy w nosie" },
  {
    id: 235,
    category: "związki frazeologiczne",
    phrase: "Mieć serce na dłoni",
  },
  { id: 236, category: "związki frazeologiczne", phrase: "Mieć z kimś kosę" },
  { id: 237, category: "związki frazeologiczne", phrase: "Niebo w gębie" },
  { id: 238, category: "związki frazeologiczne", phrase: "Pójść na całość" },
  {
    id: 239,
    category: "związki frazeologiczne",
    phrase: "Pójść po rozum do głowy",
  },
  {
    id: 240,
    category: "związki frazeologiczne",
    phrase: "Przegapić swoją szansę",
  },
  {
    id: 241,
    category: "związki frazeologiczne",
    phrase: "Porywać się z motyką na słońce",
  },
  {
    id: 242,
    category: "związki frazeologiczne",
    phrase: "Robić dobrą minę do złej gry",
  },
  {
    id: 243,
    category: "związki frazeologiczne",
    phrase: "Rzucać grochem o ścianę",
  },
  {
    id: 244,
    category: "związki frazeologiczne",
    phrase: "Rzucać perły przed wieprze",
  },
  {
    id: 245,
    category: "związki frazeologiczne",
    phrase: "Rzucać słowa na wiatr",
  },
  {
    id: 246,
    category: "związki frazeologiczne",
    phrase: "Spalić za sobą mosty",
  },
  {
    id: 247,
    category: "związki frazeologiczne",
    phrase: "Siedzieć jak na szpilkach",
  },
  {
    id: 248,
    category: "związki frazeologiczne",
    phrase: "Siedzieć z założonymi rękami",
  },
  { id: 249, category: "związki frazeologiczne", phrase: "Stawać na głowie" },
  { id: 250, category: "związki frazeologiczne", phrase: "Słomiany zapał" },
  {
    id: 251,
    category: "związki frazeologiczne",
    phrase: "Trzymać język za zębami",
  },
  {
    id: 252,
    category: "związki frazeologiczne",
    phrase: "Wbić komuś nóż w plecy",
  },
  {
    id: 253,
    category: "związki frazeologiczne",
    phrase: "Wpaść jak śliwka w kompot",
  },
  { id: 254, category: "związki frazeologiczne", phrase: "Wyjść na prostą" },
  {
    id: 255,
    category: "związki frazeologiczne",
    phrase: "Wylać dziecko z kąpielą",
  },
  {
    id: 256,
    category: "związki frazeologiczne",
    phrase: "Zawrócić komuś w głowie",
  },
  { id: 257, category: "związki frazeologiczne", phrase: "Dzień jak co dzień" },
  { id: 258, category: "związki frazeologiczne", phrase: "Podkulić ogon" },

  // Znane postacie
  { id: 259, category: "znane postacie", phrase: "Abraham Lincoln" },
  { id: 260, category: "znane postacie", phrase: "Adam Mickiewicz" },
  { id: 261, category: "znane postacie", phrase: "Albert Einstein" },
  { id: 262, category: "znane postacie", phrase: "Aleksander Wielki" },
  { id: 263, category: "znane postacie", phrase: "Barack Obama" },
  { id: 264, category: "znane postacie", phrase: "Bill Gates" },
  { id: 265, category: "znane postacie", phrase: "Charlie Chaplin" },
  { id: 266, category: "znane postacie", phrase: "Elvis Presley" },
  { id: 267, category: "znane postacie", phrase: "Fryderyk Chopin" },
  { id: 268, category: "znane postacie", phrase: "Henryk Sienkiewicz" },
  { id: 269, category: "znane postacie", phrase: "Isaac Newton" },
  { id: 270, category: "znane postacie", phrase: "Lech Wałęsa" },
  { id: 271, category: "znane postacie", phrase: "Julian Tuwim" },
  { id: 272, category: "znane postacie", phrase: "Józef Piłsudski" },
  { id: 273, category: "znane postacie", phrase: "Juliusz Cezar" },
  { id: 274, category: "znane postacie", phrase: "Kazimierz Wielki" },
  { id: 275, category: "znane postacie", phrase: "Krzysztof Ibisz" },
  { id: 276, category: "znane postacie", phrase: "Leonardo da Vinci" },
  { id: 277, category: "znane postacie", phrase: "Ludwig van Beethoven" },
  { id: 278, category: "znane postacie", phrase: "Mahatma Gandhi" },
  { id: 279, category: "znane postacie", phrase: "Maria Skłodowska Curie" },
  { id: 280, category: "znane postacie", phrase: "Mikołaj Kopernik" },
  { id: 281, category: "znane postacie", phrase: "Napoleon Bonaparte" },
  { id: 282, category: "znane postacie", phrase: "Nelson Mandela" },
  { id: 283, category: "znane postacie", phrase: "Nikola Tesla" },
  { id: 284, category: "znane postacie", phrase: "Pablo Picasso" },
  {
    id: 285,
    category: "znane postacie",
    phrase: "Stanisław August Poniatowski",
  },
  { id: 286, category: "znane postacie", phrase: "Steve Jobs" },
  { id: 287, category: "znane postacie", phrase: "Stephen Hawking" },
  { id: 288, category: "znane postacie", phrase: "Tadeusz Kościuszko" },
  { id: 289, category: "znane postacie", phrase: "Walt Disney" },
  { id: 290, category: "znane postacie", phrase: "William Shakespeare" },
  { id: 291, category: "znane postacie", phrase: "Winston Churchill" },
  { id: 292, category: "znane postacie", phrase: "Władysław Jagiełło" },
  { id: 293, category: "znane postacie", phrase: "Arystoteles" },
  { id: 294, category: "znane postacie", phrase: "Konfucjusz" },
  { id: 295, category: "znane postacie", phrase: "Leonardo DiCaprio" },

  {
    id: 296,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Bułka z masłem",
  },
  {
    id: 297,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Robić z igły widły",
  },
  {
    id: 298,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Gadać jak najęty",
  },
  {
    id: 299,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Mieć dwie lewe ręce",
  },
  {
    id: 300,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Spać jak suseł",
  },
  {
    id: 301,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Pocałować klamkę",
  },
  {
    id: 302,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Wiercić komuś dziurę w brzuchu",
  },
  { id: 303, category: "idiomy i wyrażenia potoczne", phrase: "Wyjść na jaw" },
  {
    id: 304,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Słomiany zapał",
  },
  {
    id: 305,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Łapać wiatr w żagle",
  },
  {
    id: 306,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Koń by się uśmiał",
  },
  {
    id: 307,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Nie mój cyrk nie moje małpy",
  },
  {
    id: 308,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Co ma piernik do wiatraka",
  },
  {
    id: 309,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Myśleć o niebieskich migdałach",
  },
  {
    id: 310,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Obiecywać gruszki na wierzbie",
  },
  {
    id: 311,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Nie wtykaj nosa w nie swoje sprawy",
  },
  {
    id: 312,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Dostać kota w worku",
  },
  {
    id: 313,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Głową muru nie przebijesz",
  },
  {
    id: 314,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Zjadł zęby na czymś",
  },
  {
    id: 315,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Nabić kogoś w butelkę",
  },
  { id: 316, category: "idiomy i wyrażenia potoczne", phrase: "Ręce opadają" },
  {
    id: 317,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Mieć serce jak dzwon",
  },
  {
    id: 318,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Leje jak z cebra",
  },
  {
    id: 319,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Mieć węża w kieszeni",
  },
  {
    id: 320,
    category: "idiomy i wyrażenia potoczne",
    phrase: "Rzucać grochem o ścianę",
  },

  // Wydarzenia historyczne
  {
    id: 321,
    category: "wydarzenia historyczne",
    phrase: "Bitwa pod Grunwaldem",
  },
  {
    id: 322,
    category: "wydarzenia historyczne",
    phrase: "Druga wojna światowa",
  },
  {
    id: 323,
    category: "wydarzenia historyczne",
    phrase: "Powstanie Warszawskie",
  },
  {
    id: 324,
    category: "wydarzenia historyczne",
    phrase: "Upadek muru berlińskiego",
  },
  {
    id: 325,
    category: "wydarzenia historyczne",
    phrase: "Lądowanie na Księżycu",
  },
  {
    id: 326,
    category: "wydarzenia historyczne",
    phrase: "Odkrycie Ameryki przez Kolumba",
  },
  {
    id: 327,
    category: "wydarzenia historyczne",
    phrase: "Rewolucja francuska",
  },
  {
    id: 328,
    category: "wydarzenia historyczne",
    phrase: "Pierwsza wojna światowa",
  },
  {
    id: 329,
    category: "wydarzenia historyczne",
    phrase: "Obrady Okrągłego Stołu",
  },
  { id: 330, category: "wydarzenia historyczne", phrase: "Chrzest Polski" },

  {
    id: 341,
    category: "przedmioty codziennego użytku",
    phrase: "Szczoteczka do zębów",
  },
  {
    id: 342,
    category: "przedmioty codziennego użytku",
    phrase: "Pasta do zębów",
  },
  {
    id: 343,
    category: "przedmioty codziennego użytku",
    phrase: "Żel pod prysznic",
  },
  {
    id: 345,
    category: "przedmioty codziennego użytku",
    phrase: "Płyn do naczyń",
  },
  { id: 346, category: "przedmioty codziennego użytku", phrase: "Krem do rąk" },
  {
    id: 348,
    category: "przedmioty codziennego użytku",
    phrase: "Maszynka do golenia",
  },
  {
    id: 349,
    category: "przedmioty codziennego użytku",
    phrase: "Chusteczki higieniczne nawilżane",
  },
  {
    id: 350,
    category: "przedmioty codziennego użytku",
    phrase: "Odkurzacz bezprzewodowy",
  },
  {
    id: 351,
    category: "przedmioty codziennego użytku",
    phrase: "Zestaw do manicure",
  },
  {
    id: 352,
    category: "przedmioty codziennego użytku",
    phrase: "Czajnik elektryczny bezprzewodowy",
  },
  {
    id: 353,
    category: "przedmioty codziennego użytku",
    phrase: "Młynek do kawy",
  },
  {
    id: 354,
    category: "przedmioty codziennego użytku",
    phrase: "Ładowarka do telefonu",
  },
  {
    id: 355,
    category: "przedmioty codziennego użytku",
    phrase: "Kabel USB typu C",
  },
  {
    id: 356,
    category: "przedmioty codziennego użytku",
    phrase: "Kosz na śmieci",
  },
  {
    id: 357,
    category: "przedmioty codziennego użytku",
    phrase: "Deska do krojenia",
  },
  {
    id: 358,
    category: "przedmioty codziennego użytku",
    phrase: "Zestaw pościeli",
  },
  {
    id: 359,
    category: "przedmioty codziennego użytku",
    phrase: "Płyn do płukania tkanin",
  },

  { id: 410, category: "święta i uroczystości", phrase: "Boże Narodzenie" },
  { id: 411, category: "święta i uroczystości", phrase: "Wielkanoc" },
  { id: 412, category: "święta i uroczystości", phrase: "Nowy Rok" },
  { id: 413, category: "święta i uroczystości", phrase: "Dzień Kobiet" },
  { id: 414, category: "święta i uroczystości", phrase: "Dzień Matki" },
  { id: 415, category: "święta i uroczystości", phrase: "Dzień Ojca" },
  { id: 416, category: "święta i uroczystości", phrase: "Walentynki" },
  { id: 417, category: "święta i uroczystości", phrase: "Dzień Dziecka" },
  { id: 418, category: "święta i uroczystości", phrase: "Święto Niepodległości" },
  { id: 420, category: "święta i uroczystości", phrase: "Andrzejki" },
  { id: 421, category: "święta i uroczystości", phrase: "Sylwester" },
  { id: 422, category: "święta i uroczystości", phrase: "Mikołajki" },
  { id: 423, category: "święta i uroczystości", phrase: "Dzień Nauczyciela" },
  { id: 424, category: "święta i uroczystości", phrase: "Tłusty Czwartek" },
  { id: 425, category: "święta i uroczystości", phrase: "Dzień Babci" },
  { id: 426, category: "święta i uroczystości", phrase: "Dzień Dziadka" },
  { id: 427, category: "święta i uroczystości", phrase: "Śmigus Dyngus" },
  { id: 428, category: "święta i uroczystości", phrase: "Pierwszy Dzień Wiosny" },
  { id: 429, category: "święta i uroczystości", phrase: "Zakończenie Roku Szkolnego" },
  { id: 430, category: "święta i uroczystości", phrase: "Wniebowzięcie Maryi" },
  { id: 431, category: "święta i uroczystości", phrase: "Zaduszki" },
  { id: 432, category: "święta i uroczystości", phrase: "Dzień Chłopaka" },
  { id: 433, category: "święta i uroczystości", phrase: "Halloween" },
  { id: 434, category: "święta i uroczystości", phrase: "Święto Pracy" },
  { id: 435, category: "święta i uroczystości", phrase: "Trzech Króli" },
  { id: 436, category: "święta i uroczystości", phrase: "Dzień Ziemi" },
  { id: 445, category: "święta i uroczystości", phrase: "Dzień Taty" },
  { id: 447, category: "święta i uroczystości", phrase: "Dzień Kobiet" },
  { id: 448, category: "święta i uroczystości", phrase: "Dzień Dziecka" },
  { id: 449, category: "święta i uroczystości", phrase: "Dzień Chłopaka" },

  { id: 500, category: "łamańce językowe", phrase: "Szły pchły koło wody pchła pchłę pchła do wody" },
  { id: 501, category: "łamańce językowe", phrase: "W czasie suszy szosa sucha" },
  { id: 502, category: "łamańce językowe", phrase: "Cesarz czesze cesarzową" },

  { id: 503, category: "nazwy dań", phrase: "Pyzy z mięsem" },
  { id: 504, category: "nazwy dań", phrase: "Racuchy z jabłkami" },
  { id: 505, category: "nazwy dań", phrase: "Oscypek z żurawiną" },

  { id: 506, category: "nazwy geograficzne", phrase: "Puszcza Białowieska" },
  { id: 507, category: "nazwy geograficzne", phrase: "Wielkie Jeziora Mazurskie" },
  { id: 508, category: "nazwy geograficzne", phrase: "Bieszczady" },

  { id: 509, category: "polskie seriale", phrase: "Przyjaciółki" },
  { id: 510, category: "polskie seriale", phrase: "Wiedźmin" },
  { id: 511, category: "polskie seriale", phrase: "Alternatywy cztery" },

  { id: 512, category: "polskie teleturnieje", phrase: "Idol" },
  { id: 513, category: "polskie teleturnieje", phrase: "Szansa na sukces" },
  { id: 514, category: "polskie teleturnieje", phrase: "Tak to leciało" },

  { id: 515, category: "polskie województwa", phrase: "Zachodniopomorskie" },

  { id: 516, category: "postacie z bajek", phrase: "Koziołek Matołek" },
  { id: 517, category: "postacie z bajek", phrase: "Miś Uszatek" },
  { id: 518, category: "postacie z bajek", phrase: "Reksio" },

  { id: 519, category: "przysłowia", phrase: "Baba z wozu koniom lżej" },
  { id: 520, category: "przysłowia", phrase: "Dla chcącego nic trudnego" },
  { id: 521, category: "przysłowia", phrase: "Nie ma róży bez kolców" },

  { id: 522, category: "tytuły filmów", phrase: "Avengers" },
  { id: 523, category: "tytuły filmów", phrase: "Czas Apokalipsy" },
  { id: 524, category: "tytuły filmów", phrase: "Django" },

  { id: 525, category: "tytuły książek", phrase: "Kamienie na szaniec" },
  { id: 526, category: "tytuły książek", phrase: "Ludzie bezdomni" },
  { id: 527, category: "tytuły książek", phrase: "Opowieści z Narnii" },

  { id: 528, category: "związki frazeologiczne", phrase: "Nie kiwnąć palcem" },
  { id: 529, category: "związki frazeologiczne", phrase: "Jak grom z jasnego nieba" },
  { id: 530, category: "związki frazeologiczne", phrase: "Chodzić spać z kurami" },

  { id: 531, category: "znane postacie", phrase: "Juliusz Słowacki" },
  { id: 532, category: "znane postacie", phrase: "Galileusz" },
  { id: 533, category: "znane postacie", phrase: "Jan Paweł Drugi" },

  { id: 534, category: "idiomy i wyrażenia potoczne", phrase: "Siedzieć na walizkach" },
  { id: 535, category: "idiomy i wyrażenia potoczne", phrase: "Wpuścić kogoś w maliny" },
  { id: 536, category: "idiomy i wyrażenia potoczne", phrase: "Robić kogoś w konia" },

  { id: 537, category: "wydarzenia historyczne", phrase: "Unia Lubelska" },
  { id: 538, category: "wydarzenia historyczne", phrase: "Bitwa pod Wiedniem" },
  { id: 539, category: "wydarzenia historyczne", phrase: "Reformacja" },

  { id: 540, category: "przedmioty codziennego użytku", phrase: "Kuchenka mikrofalowa" },
  { id: 541, category: "przedmioty codziennego użytku", phrase: "Szczotka do włosów" },
  { id: 542, category: "przedmioty codziennego użytku", phrase: "Parasol przeciwdeszczowy" },

  { id: 543, category: "święta i uroczystości", phrase: "Dzień Wszystkich Świętych" },
  { id: 544, category: "święta i uroczystości", phrase: "Boże Ciało" },
  { id: 545, category: "święta i uroczystości", phrase: "Dzień Zakochanych" },

  { id: 564, category: "przedmioty codziennego użytku", phrase: "Szczotka do zamiatania" },
  { id: 565, category: "przedmioty codziennego użytku", phrase: "Ściereczka z mikrofibry" },
  { id: 566, category: "przedmioty codziennego użytku", phrase: "Żelazko parowe" },

  { id: 567, category: "postacie z bajek", phrase: "Kaczor Donald" },
  { id: 568, category: "postacie z bajek", phrase: "Goofy" },
  { id: 569, category: "postacie z bajek", phrase: "Pluto" },

  { id: 546, category: "związki frazeologiczne", phrase: "Złapać byka za rogi" },
  { id: 547, category: "związki frazeologiczne", phrase: "Wyssać coś z palca" },
  { id: 548, category: "związki frazeologiczne", phrase: "Mieć wilczy apetyt" },

  { id: 549, category: "tytuły filmów", phrase: "Lot nad kukułczym gniazdem" },
  { id: 551, category: "tytuły filmów", phrase: "Podziemny krąg" },

  { id: 552, category: "tytuły książek", phrase: "Bracia Karamazow" },
  { id: 553, category: "tytuły książek", phrase: "Sto lat samotności" },
  { id: 554, category: "tytuły książek", phrase: "Pachnidło" },
];

const vowels = ["A", "E", "I", "O", "U", "Y", "Ą", "Ę", "Ó"];

const values = [
  "-100%",
  250,
  400,
  300,
  1500,
  600,
  700,
  800,
  "STOP",
  600,
  200,
  100,
  1000,
  500,
  800,
  150,
];

module.exports = { initialPhrases, vowels, values };
